### ISSUE TITLE
Learning from your scripts

### ISSUE THREAD

**Issue by Lomias0531** [Whiplash141/SpaceEngineersScripts#5]
Hi, sorry to bother you.
I'm a Space Engineers player, and is now starting to write my own scripts. When I was studying your radar script, I found that the scheduler class in it is really useful, solved a big problem of my project. So I was wondering if I can try applying it to my script, but of course I'll make modifications to suit my needs? I'll make notifications that this part is learning from you when my script is published.
Big thanks and looking forward to your reply!

**Comment by Whiplash141** [comment]
Of course 😄 

That is what this code is here for! Also, sorry for the delay, GitHub didn't notify me of any of these issues being created and I'm trying to figure out why...

I've uploaded my newest version of my scheduler here: https://github.com/Whiplash141/SpaceEngineersScripts/blob/master/Classes/Scheduler.cs
