### ISSUE TITLE
Uninitialized ImmurableArray received via IGC will cause exception

### ISSUE THREAD

**Issue by krypt-lynx** [Whiplash141/SpaceEngineersScripts#6]
`ImmutableArray` is a struct, and has zero initialized state (available for all structs), but such considered to be invalid
You can create such invalid instance by calling `default(ImmutableArray<TItem>)`

https://github.com/Whiplash141/SpaceEngineersScripts/blob/86dd0f6f0bb26930de962b08c12487595f391431/Released/turret_radar.cs#L399

You can fix it using `payloadArray.IsDefault`

For example, in this way:
```cs
                var payloadArray = (ImmutableArray<MyTuple<byte, long, Vector3D, double>>)messageData;
                if (payloadArray.IsDefault) {
                    foreach (var payload in payloadArray)
                    {
                        ProcessDataPacketWhips(message.Source, (TargetRelation)payload.Item1, payload.Item2, payload.Item3);
                    }
                }
```

**Comment by Whiplash141** [comment]
Fixed
